# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35b1f17148ac17040d736cdadf8789ffaf56f8733abc551359695b342656a1b3f648bf31d899af9857d9c0802455bb17bd1a29a8eb4c526bd3dc55fc7063c698

test:
  secret_key_base: c7b6b46fa519189b240f39307150476815b829675853a8c7a1d8a3bad1132c8850257bb1c8ea2bb951da44b034d9d1603de902f494c0afc714549a739f80a904

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
